apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: moideenshacp/e-auth
          ports:
            - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort  
  selector:
    app: auth-service
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 30004
