name: CI-CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 1: Build Docker Images for Each Service
      - name: Build auth-service Docker image
        run: |
          cd auth-service
          docker build -t moideenshacp/e-auth .
          docker push moideenshacp/e-auth

      - name: Build product-service Docker image
        run: |
          cd product-service
          docker build -t moideenshacp/e-product-service .
          docker push moideenshacp/e-product-service

      - name: Build order-service Docker image
        run: |
          cd order-service
          docker build -t moideenshacp/e-order-service .
          docker push moideenshacp/e-order-service
